[cluster]
    # 集群客户端配置，常用于调试使用
    [cluster.client]
        # 实例ID，网关集群中唯一。不填写默认自动生成唯一的实例ID
        id = ""
        # 实例名称
        name = "client"
        # 编解码器。可选：json | proto
        codec = "json"

[packet]
    # 字节序，默认为big。可选：little | big
    byteOrder = "big"
    # 路由字节数，默认为2字节
    routeBytes = 4
    # 序列号字节数，默认为2字节
    seqBytes = 4
    # 消息字节数，默认为5000字节
    bufferBytes = 100000

[log]
    # 日志输出级别，可选：debug | info | warn | error | fatal | panic
    level = "warn"
    # 堆栈的最低输出级别，可选：debug | info | warn | error | fatal | panic
    stackLevel = "error"
    # 时间格式，标准库时间格式
    timeFormat = "2006/01/02 15:04:05.000000"
    # 输出栈的跳过深度
    callSkip = 2
    # 是否启用调用文件全路径
    callFullPath = true
    # 日志输出终端（数组和对象两种配置形式任选其一）
    terminals = ["console", "file"]
    # 控制台同步器配置
    [log.console]
        # 日志输出格式，可选：text | json
        format = "text"
    # 文件同步器配置
    [log.file]
        # 输出文件路径
        path = "./log/due.log"
        # 日志输出格式，可选：text | json
        format = "text"
        # 文件最大留存时间，d:天、h:时、m:分、s:秒
        maxAge = "7d"
        # 文件最大尺寸限制，支持单位： B | K | KB | M | MB | G | GB | T | TB | P | PB | E | EB | Z | ZB，默认为100M
        maxSize = "100M"
        # 文件翻转方式，可选：none | year | month | week | day | hour，默认为none
        rotate = "day"
        # 文件翻转时是否对文件进行压缩
        compress = false

[network]
    [network.ws]
        [network.ws.client]
            # 拨号地址
            url = "ws://127.0.0.1:3553"
            # 握手超时时间，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为10s
            handshakeTimeout = "10s"
            # 心跳间隔时间。设置为0则不启用心跳检测，支持单位：纳秒（ns）、微秒（us | µs）、毫秒（ms）、秒（s）、分（m）、小时（h）、天（d）。默认为10s
            heartbeatInterval = "10s"
    [network.tcp]
        [network.tcp.client]
            # 拨号地址
            addr = "127.0.0.1:3553"
            # 拨号超时时间，默认5s
            timeout = "5s"
            # 心跳间隔时间（秒），默认为10秒。设置为0则不启用心跳检测
            heartbeatInterval = 0
